// #region actionApp
export const ACTION_APP_SAVE_USER = 'ACTION_APP_SAVE_USER';
export const ACTION_APP_UPDATE_TABBAR_VISIBLE = 'ACTION_APP_UPDATE_TABBAR_VISIBLE';

export const ACTION_GET_API_USER_START = 'ACTION_GET_API_USER_START';
export const ACTION_GET_API_USER_CANCEL = 'ACTION_GET_API_USER_CANCEL';
export const ACTION_GET_API_USER_SUCCESS = 'ACTION_GET_API_USER_SUCCESS';
export const ACTION_GET_API_USER_FAILURE = 'ACTION_GET_API_USER_FAILURE';

export const ACTION_POST_API_UPDATE_USER_START = 'ACTION_POST_API_UPDATE_USER_START';
export const ACTION_POST_API_UPDATE_USER_CANCEL = 'ACTION_POST_API_UPDATE_USER_CANCEL';
export const ACTION_POST_API_UPDATE_USER_SUCCESS = 'ACTION_POST_API_UPDATE_USER_SUCCESS';
export const ACTION_POST_API_UPDATE_USER_FAILURE = 'ACTION_POST_API_UPDATE_USER_FAILURE';

export const ACTION_POST_API_UPLOAD_USER_AVATAR_START = 'ACTION_POST_API_UPLOAD_USER_AVATAR_START';
export const ACTION_POST_API_UPLOAD_USER_AVATAR_CANCEL = 'ACTION_POST_API_UPLOAD_USER_AVATAR_CANCEL';
export const ACTION_POST_API_UPLOAD_USER_AVATAR_SUCCESS = 'ACTION_POST_API_UPLOAD_USER_AVATAR_SUCCESS';
export const ACTION_POST_API_UPLOAD_USER_AVATAR_FAILURE = 'ACTION_POST_API_UPLOAD_USER_AVATAR_FAILURE';

export const ACTION_UPDATE_USER_LOCATION = 'ACTION_UPDATE_USER_LOCATION';

export const ACTION_SAVE_DEVICE_DETAIL = 'ACTION_INFO_DEVICE_DETAIL';
// #endregion

// #region actionSignIn
export const ACTION_POST_API_SIGNIN_START = 'ACTION_POST_API_SIGNIN_START';
export const ACTION_POST_API_SIGNIN_CANCEL = 'ACTION_POST_API_SIGNIN_CANCEL';
export const ACTION_POST_API_SIGNIN_SUCCESS = 'ACTION_POST_API_SIGNIN_SUCCESS';
export const ACTION_POST_API_SIGNIN_FAILURE = 'ACTION_POST_API_SIGNIN_FAILURE';
// #endregion

// #region actionForgotPassword
export const ACTION_POST_API_FORGOT_PASSWORD_START = 'ACTION_POST_API_FORGOT_PASSWORD_START';
export const ACTION_POST_API_FORGOT_PASSWORD_CANCEL = 'ACTION_POST_API_FORGOT_PASSWORD_CANCEL';
export const ACTION_POST_API_FORGOT_PASSWORD_SUCCESS = 'ACTION_POST_API_FORGOT_PASSWORD_SUCCESS';
export const ACTION_POST_API_FORGOT_PASSWORD_FAILURE = 'ACTION_POST_API_FORGOT_PASSWORD_FAILURE';
// #endregion

// #region actionSignUp
export const ACTION_POST_API_SIGNUP_START = 'ACTION_POST_API_SIGNUP_START';
export const ACTION_POST_API_SIGNUP_CANCEL = 'ACTION_POST_API_SIGNUP_CANCEL';
export const ACTION_POST_API_SIGNUP_SUCCESS = 'ACTION_POST_API_SIGNUP_SUCCESS';
export const ACTION_POST_API_SIGNUP_FAILURE = 'ACTION_POST_API_SIGNUP_FAILURE';
// #endregion

// #region actionScanQR
export const ACTION_SCANQR_UPDATE_CAMERA_VISIBLE = 'ACTION_SCANQR_UPDATE_CAMERA_VISIBLE';
export const ACTION_SCANQR_UPDATE_CAMERA_REACTIVE = 'ACTION_SCANQR_UPDATE_CAMERA_REACTIVE';

export const ACTION_POST_API_CLOCKIN_START = 'ACTION_POST_API_CLOCKIN_START';
export const ACTION_POST_API_CLOCKIN_CANCEL = 'ACTION_POST_API_CLOCKIN_CANCEL';
export const ACTION_POST_API_CLOCKIN_SUCCESS = 'ACTION_POST_API_CLOCKIN_SUCCESS';
export const ACTION_POST_API_CLOCKIN_FAILURE = 'ACTION_POST_API_CLOCKIN_FAILURE';
// #endregion

// #region Access Log
export const ACTION_FETCH_ACCESS_LOG_START = 'ACTION_FETCH_ACCESS_LOG_START';
export const ACTION_FETCH_ACCESS_LOG_CANCEL = 'ACTION_FETCH_ACCESS_LOG_CANCEL';
export const ACTION_FETCH_ACCESS_LOG_SUCCESS = 'ACTION_FETCH_ACCESS_LOG_SUCCESS';
export const ACTION_FETCH_ACCESS_LOG_FAILURE = 'ACTION_FETCH_ACCESS_LOG_FAILURE';
// #endregion

// #region Change Pass
export const ACTION_POST_CHANGE_PASS_START = 'ACTION_POST_CHANGE_PASS_START';
export const ACTION_POST_CHANGE_PASS_CANCEL = 'ACTION_POST_CHANGE_PASS_CANCEL';
export const ACTION_POST_CHANGE_PASS_SUCCESS = 'ACTION_POST_CHANGE_PASS_SUCCESS';
export const ACTION_POST_CHANGE_PASS_FAILURE = 'ACTION_POST_CHANGE_PASS_FAILURE';
// #endregion

// #region USER: GET LIST 
export const ACTION_GET_LIST_USER = 'ACTION_GET_LIST_USER';
export const ACTION_GET_LIST_USER_REQUEST = `${ACTION_GET_LIST_USER}_REQUEST`;
export const ACTION_GET_LIST_USER_SUCCESS = `${ACTION_GET_LIST_USER}_SUCCESS`;
export const ACTION_GET_LIST_USER_FAILURE = `${ACTION_GET_LIST_USER}_FAILURE`;
// #endregion

// #region USER: ADD
export const ACTION_ADD_USER = 'ACTION_ADD_USER';
export const ACTION_ADD_USER_REQUEST = `${ACTION_ADD_USER}_REQUEST`;
export const ACTION_ADD_USER_SUCCESS = `${ACTION_ADD_USER}_SUCCESS`;
export const ACTION_ADD_USER_FAILURE = `${ACTION_ADD_USER}_FAILURE`;
// #endregion

// #region USER: UPDATE
export const ACTION_UPDATE_USER = 'ACTION_UPDATE_USER';
export const ACTION_UPDATE_USER_REQUEST = `${ACTION_UPDATE_USER}_REQUEST`;
export const ACTION_UPDATE_USER_SUCCESS = `${ACTION_UPDATE_USER}_SUCCESS`;
export const ACTION_UPDATE_USER_FAILURE = `${ACTION_UPDATE_USER}_FAILURE`;
export const ACTION_UPDATE_USER_RESET = `${ACTION_UPDATE_USER}_RESET`;
// #endregion

// #region USER: REMOVE
export const ACTION_REMOVE_USER = 'ACTION_REMOVE_USER';
export const ACTION_REMOVE_USER_REQUEST = `${ACTION_REMOVE_USER}_REQUEST`;
export const ACTION_REMOVE_USER_SUCCESS = `${ACTION_REMOVE_USER}_SUCCESS`;
export const ACTION_REMOVE_USER_FAILURE = `${ACTION_REMOVE_USER}_FAILURE`;
export const ACTION_REMOVE_USER_RESET = `${ACTION_REMOVE_USER}_RESET`;
// #endregion

// #region DEVICE: GET LIST 
export const ACTION_GET_LIST_DEVICE = 'ACTION_GET_LIST_DEVICE';
export const ACTION_GET_LIST_DEVICE_REQUEST = `${ACTION_GET_LIST_DEVICE}_REQUEST`;
export const ACTION_GET_LIST_DEVICE_SUCCESS = `${ACTION_GET_LIST_DEVICE}_SUCCESS`;
export const ACTION_GET_LIST_DEVICE_FAILURE = `${ACTION_GET_LIST_DEVICE}_FAILURE`;
// #endregion

// #region DEVICE: ADD
export const ACTION_ADD_DEVICE = 'ACTION_ADD_DEVICE';
export const ACTION_ADD_DEVICE_REQUEST = `${ACTION_ADD_DEVICE}_REQUEST`;
export const ACTION_ADD_DEVICE_SUCCESS = `${ACTION_ADD_DEVICE}_SUCCESS`;
export const ACTION_ADD_DEVICE_FAILURE = `${ACTION_ADD_DEVICE}_FAILURE`;
// #endregion

// #region DEVICE: UPDATE
export const ACTION_UPDATE_DEVICE = 'ACTION_UPDATE_DEVICE';
export const ACTION_UPDATE_DEVICE_REQUEST = `${ACTION_UPDATE_DEVICE}_REQUEST`;
export const ACTION_UPDATE_DEVICE_SUCCESS = `${ACTION_UPDATE_DEVICE}_SUCCESS`;
export const ACTION_UPDATE_DEVICE_FAILURE = `${ACTION_UPDATE_DEVICE}_FAILURE`;
export const ACTION_UPDATE_DEVICE_RESET = `${ACTION_UPDATE_DEVICE}_RESET`;
// #endregion

// #region DEVICE: REMOVE
export const ACTION_REMOVE_DEVICE = 'ACTION_REMOVE_DEVICE';
export const ACTION_REMOVE_DEVICE_REQUEST = `${ACTION_REMOVE_DEVICE}_REQUEST`;
export const ACTION_REMOVE_DEVICE_SUCCESS = `${ACTION_REMOVE_DEVICE}_SUCCESS`;
export const ACTION_REMOVE_DEVICE_FAILURE = `${ACTION_REMOVE_DEVICE}_FAILURE`;
export const ACTION_REMOVE_DEVICE_RESET = `${ACTION_REMOVE_DEVICE}_RESET`;
// #endregion

// #region DEVICE: TOGGLE USER
export const ACTION_TOGGLE_USER_IN_DEVICE = 'ACTION_TOGGLE_USER_IN_DEVICE';
export const ACTION_TOGGLE_USER_IN_DEVICE_REQUEST = `${ACTION_TOGGLE_USER_IN_DEVICE}_REQUEST`;
export const ACTION_TOGGLE_USER_IN_DEVICE_SUCCESS = `${ACTION_TOGGLE_USER_IN_DEVICE}_SUCCESS`;
export const ACTION_TOGGLE_USER_IN_DEVICE_FAILURE = `${ACTION_TOGGLE_USER_IN_DEVICE}_FAILURE`;
// #endregion

//#region Kenny
export const ACTION_GET_LOGINLOGS='ACTION_GET_LOGINLOGS';
export const ACTION_GET_LOGINLOGS_START=`${ACTION_GET_LOGINLOGS}_START`;
export const ACTION_GET_LOGINLOGS_SUCCESS=`${ACTION_GET_LOGINLOGS}_SUCCESS`;
export const ACTION_GET_LOGINLOGS_ERROR=`${ACTION_GET_LOGINLOGS}_ERROR`;

export const ACTION_GET_DOORLOGS='ACTION_GET_DOORLOGS';
export const ACTION_GET_DOORLOGS_START=`${ACTION_GET_DOORLOGS}_START`;
export const ACTION_GET_DOORLOGS_SUCCESS=`${ACTION_GET_DOORLOGS}_SUCCESS`;
export const ACTION_GET_DOORLOGS_ERROR=`${ACTION_GET_DOORLOGS}_ERROR`

export const ACTION_POST_DOORFILTER='ACTION_POST_DOORFILTER';
export const ACTION_POST_DOORFILTER_START =`${ACTION_POST_DOORFILTER}_START`
export const ACTION_POST_DOORFILTER_SUCCESS =`${ACTION_POST_DOORFILTER}_sUCCESS`
export const ACTION_POST_DOORFILTER_ERROR =`${ACTION_POST_DOORFILTER}_ERROR`

export const ACTION_POST_LOGINFILTER='ACTION_POST_LOGINFILTER';
export const ACTION_POST_LOGINFILTER_START =`${ACTION_POST_LOGINFILTER}_START`
export const ACTION_POST_LOGINFILTER_SUCCESS =`${ACTION_POST_LOGINFILTER}_sUCCESS`
export const ACTION_POST_LOGINFILTER_ERROR =`${ACTION_POST_LOGINFILTER}_ERROR`
//#endregion

