// #region actionApp
export const ACTION_APP_SAVE_USER = 'ACTION_APP_SAVE_USER'
export const ACTION_APP_UPDATE_TABBAR_VISIBLE = 'ACTION_APP_UPDATE_TABBAR_VISIBLE'

export const ACTION_GET_API_USER_START = 'ACTION_GET_API_USER_START'
export const ACTION_GET_API_USER_CANCEL = 'ACTION_GET_API_USER_CANCEL'
export const ACTION_GET_API_USER_SUCCESS = 'ACTION_GET_API_USER_SUCCESS'
export const ACTION_GET_API_USER_FAILURE = 'ACTION_GET_API_USER_FAILURE'

export const ACTION_POST_API_UPDATE_USER_START = 'ACTION_POST_API_UPDATE_USER_START'
export const ACTION_POST_API_UPDATE_USER_CANCEL = 'ACTION_POST_API_UPDATE_USER_CANCEL'
export const ACTION_POST_API_UPDATE_USER_SUCCESS = 'ACTION_POST_API_UPDATE_USER_SUCCESS'
export const ACTION_POST_API_UPDATE_USER_FAILURE = 'ACTION_POST_API_UPDATE_USER_FAILURE'

export const ACTION_POST_API_UPLOAD_USER_AVATAR_START = 'ACTION_POST_API_UPLOAD_USER_AVATAR_START'
export const ACTION_POST_API_UPLOAD_USER_AVATAR_CANCEL = 'ACTION_POST_API_UPLOAD_USER_AVATAR_CANCEL'
export const ACTION_POST_API_UPLOAD_USER_AVATAR_SUCCESS = 'ACTION_POST_API_UPLOAD_USER_AVATAR_SUCCESS'
export const ACTION_POST_API_UPLOAD_USER_AVATAR_FAILURE = 'ACTION_POST_API_UPLOAD_USER_AVATAR_FAILURE'

export const ACTION_UPDATE_USER_LOCATION = 'ACTION_UPDATE_USER_LOCATION'

export const ACTION_SAVE_DEVICE_DETAIL = 'ACTION_INFO_DEVICE_DETAIL'
// #endregion

// #region actionSignIn
export const ACTION_POST_API_SIGNIN_START = 'ACTION_POST_API_SIGNIN_START'
export const ACTION_POST_API_SIGNIN_CANCEL = 'ACTION_POST_API_SIGNIN_CANCEL'
export const ACTION_POST_API_SIGNIN_SUCCESS = 'ACTION_POST_API_SIGNIN_SUCCESS'
export const ACTION_POST_API_SIGNIN_FAILURE = 'ACTION_POST_API_SIGNIN_FAILURE'
// #endregion

// #region actionForgotPassword
export const ACTION_POST_API_FORGOT_PASSWORD_START = 'ACTION_POST_API_FORGOT_PASSWORD_START'
export const ACTION_POST_API_FORGOT_PASSWORD_CANCEL = 'ACTION_POST_API_FORGOT_PASSWORD_CANCEL'
export const ACTION_POST_API_FORGOT_PASSWORD_SUCCESS = 'ACTION_POST_API_FORGOT_PASSWORD_SUCCESS'
export const ACTION_POST_API_FORGOT_PASSWORD_FAILURE = 'ACTION_POST_API_FORGOT_PASSWORD_FAILURE'
// #endregion

// #region actionSignUp
export const ACTION_POST_API_SIGNUP_START = 'ACTION_POST_API_SIGNUP_START'
export const ACTION_POST_API_SIGNUP_CANCEL = 'ACTION_POST_API_SIGNUP_CANCEL'
export const ACTION_POST_API_SIGNUP_SUCCESS = 'ACTION_POST_API_SIGNUP_SUCCESS'
export const ACTION_POST_API_SIGNUP_FAILURE = 'ACTION_POST_API_SIGNUP_FAILURE'
// #endregion

// #region Change Pass
export const ACTION_POST_CHANGE_PASS_START = 'ACTION_POST_CHANGE_PASS_START'
export const ACTION_POST_CHANGE_PASS_CANCEL = 'ACTION_POST_CHANGE_PASS_CANCEL'
export const ACTION_POST_CHANGE_PASS_SUCCESS = 'ACTION_POST_CHANGE_PASS_SUCCESS'
export const ACTION_POST_CHANGE_PASS_FAILURE = 'ACTION_POST_CHANGE_PASS_FAILURE'
// #endregion

export const ACTION_SET_CURRENT_SCREEN = 'SET_CURRENT_SCREEN'
// Ui
export const ACTION_PUSH = 'PUSH'
export const ACTION_SET_PUSH = 'SET_PUSH'
export const ACTION_TOAST = 'TOAST'
export const ACTION_SET_TOAST = 'SET_TOAST'
// System
export const ACTION_UPDATE_NETWORK = 'UPDATE_NETWORK'
export const ACTION_UPDATE_KEYBOARD = 'UPDATE_KEYBOARD'
export const ACTION_UPDATE_KEYBOARD_HEIGHT = 'UPDATE_KEYBOARD_HEIGHT'
export const ACTION_UPDATE_BOTTOM_TABS_HEIGHT = 'UPDATE_BOTTOM_TABS_HEIGHT'
//
export const ACTION_GET_SERVER_CONNECTION = 'GET_SERVER_CONNECTION'
export const ACTION_GET_SERVER_CONNECTION_SUCCESS = 'GET_SERVER_CONNECTION_SUCCESS'