//#region List User 
export const ACTION_GET_LISTUSER_START     ='ACTION_GET_LISTUSER_START'
export const ACTION_GET_LISTUSER_SUCCESS   ='ACTION_GET_LISTUSER_SUCCESS'
export const ACTION_GET_LISTUSER_ERROR     ='ACTION_GET_LISTUSER_ERROR'
export const ACTION_GET_LISTUSER_CANCEL    ='ACTION_GET_LISTUSER_CANCEL'
//#endregion List User

