export const Icons = {
  icFacebookSignup: require('../assets/icons/icFacebookSignup.png'),
  icGoogleSignup: require('../assets/icons/icGoogleSignup.png'),
  icCamera: require('../assets/icons/icCamera.png'),
  icCheckSignup: require('../assets/icons/icCheckSignup.png'),
  icClock: require('../assets/icons/icClock.png'),
  icBack: require('../assets/icons/icBackSignup.png'),
  icBackWhite: require('../assets/icons/icBackSignupWhite.png'),
  icLock: require('../assets/icons/icLock.png'),
  icMyLocation: require('../assets/icons/icMylocation.png'),
  icRunningButon: require('../assets/icons/icRunning.png'),
  icStartButton: require('../assets/icons/icStart.png'),
  icStop: require('../assets/icons/icStop.png'),
  icPace: require('../assets/icons/icPace.png'),
  icPlayButton: require('../assets/icons/icPlayButton.png'),
  icPauseButton: require('../assets/icons/icRunning.png'),
  icResumeButton: require('../assets/icons/icPlayButton.png'),
  icLogout: require('../assets/icons/icLogout.png'),
  icKing: require('../assets/icons/imgKing.png'),
  icClose: require('../assets/icons/icClose.png'),
  icBookmark: require('../assets/icons/icBookmarkBlack.png'),
  icBookmarkWhite: require('../assets/icons/icBookmarkLine.png'),
  icBookmarked: require('../assets/icons/imgBookmark.png'),
  icScearch: require('../assets/icons/icSearch.png'),
  icMap: require('../assets/icons/icMap.png'),
  icMenu: require('../assets/icons/icMenu.png'),
  icMusicStop: require('../assets/icons/icMusicStop.png'),
  icSetting: require('../assets/icons/icSetting.png'),
  icSaveResult: require('../assets/icons/icSaveStop.png'),
  icShare: require('../assets/icons/icShareStopResultnotreached.png'),
  icResetTime: require('../assets/icons/group21.png'),
  icRunStop: require('../assets/icons/icRunStop.png'),
  icPeople: require('../assets/icons/imgPeople.png'),
  icAwards: require('../assets/icons/ic_awards.png'),
  icBookmarkGray: require('../assets/icons/icBookChallenges.png'),
  icTime: require('../assets/icons/icTime.png'),
  icArrowRight: require('../assets/icons/icArrowRight.png'),
  icgroup30: require('../assets/icons/group30.png'),
  icgroup34: require('../assets/icons/group34.png'),
  icgroup36: require('../assets/icons/group36.png'),
  icgroup38: require('../assets/icons/group38.png'),
  icgroup40: require('../assets/icons/group40.png'),
  icgroup42: require('../assets/icons/group42.png'),
  iconVN: require('../assets/icons/icVietnamFlag.png'),
  iconSP: require('../assets/icons/icSingaporeFlag.png'),
  icDeadline: require('../assets/icons/icDeadline.png'),
  icMale_checked: require('../assets/icons/icMaleBlue.png'),
  icMale_unchecked: require('../assets/icons/icMaleGrey.png'),
  icFemale_checked: require('../assets/icons/icFemaleBlue.png'),
  icFemale_unchecked: require('../assets/icons/icFemaleGrey.png'),
  icParticipant: require('../assets/icons/icParticipant.png'),
  icValidityOrange: require('../assets/icons/icValidityOrange.png'),
  icValidityBlue: require('../assets/icons/icValidityBlue.png'),
  icReward: require('../assets/icons/icReward.png'),
  icAbout: require('../assets/icons/icAbout.png'),
  icDown: require('../assets/icons/icDown.png'),
  icKingWhiteBorder: require('../assets/icons/icKing.png'),
  icKingProfile: require('../assets/icons/icKingProfile.png'),
  icHeightProfile: require('../assets/icons/icHeightProfile.png'),
  icWeightProfile: require('../assets/icons/icWeightProfile.png')
}

export const Logos = {
  logo3: require('../assets/logos/imgLogoSplashscreen.png'),
  logoMove: require('../assets/logos/imgMove.png'),
  logoLiv3ly: require('../assets/logos/imgLogoHome.png')
}

export const Backgrounds = {
  screen1: require('../assets/images/imgOnboarding1.jpg'),
  screen2: require('../assets/images/imgOnboarding2.jpg'),
  screen3: require('../assets/images/imgOnboarding3.jpg'),
  quickStart: require('../assets/images/imgBgQuickStart.jpg'),
  quickStartFull: require('../assets/images/imgBgQuickstartFull.jpg'),
  start1: require('../assets/images/imgStartBg1.png'),
  start2: require('../assets/images/imgStartBg2.png'),
  imgBgConfigration: require('../assets/images/imgVirtualBlurBg.png'),
  startHCM: require('../assets/images/imgStartBg1.png'),
  startSG: require('../assets/images/imgStartBgSingapore.png'),
  profileBg: require('../assets/images/imgMyProfileBg.jpg'),
  challengesPopupBg: require('../assets/images/imgChallengesPopup.png')
}

export const Images = {
  checkEmail: require('../assets/images/group6.png'),
  bgEvent: require('../assets/images/imgDalatUltraTrailEvents.png'),
  bgEventTP: require('../assets/images/imgTienPhongMarathonEvents.png'),
  ava1MyChallenges: require('../assets/images/imgAvatar1Mychallenges.png'),
  ava2MyChallenges: require('../assets/images/imgAvatar2Mychallenges.png'),
  ava3MyChallenges: require('../assets/images/imgAvatar3Mychallenges.png'),
  ava4MyChallenges: require('../assets/images/imgAvatar4Mychallenges.png'),
  ava5MyChallenges: require('../assets/images/imgAvatar5Mychallenges.png'),
  imgLossBg: require('../assets/images/imgLoseBg.png'),
  imgSuccBg: require('../assets/images/imgKimlometersStopResultcompleted.png'),
  imgMapLoss: require('../assets/images/mapsLoss.png'),
  imgMapSucc: require('../assets/images/mapsSucc.png'),
  imgBgEventDetails: require('../assets/images/bgDetailsEvents.png'),
  imgVirtualPopupBg: require('../assets/images/imgVirtualPopupBg.png'),
  imgVirtualTextCongratulations: require('../assets/images/imgStopCongratulation.png'),
  imgVirtualLine: require('../assets/images/imgVirtualLine.png'),
  imgStopPopupBg: require('../assets/images/imgStopPopupBg.png'),
  placeHoder: require('../assets/images/imgVirtualDefault.png'),
  imgReward: require('../assets/images/imgReward.png')
}

export const Clips = {
  splashScreen: require('../assets/videos/logoSplashscreen2.json')
}
