const Icons = {
  add: require('../assets/icons/icPlus.png'),
  address: require('../assets/icons/icAdrress.png'),
  back: require('../assets/icons/icBack.png'),
  call: require('../assets/icons/btnCall.png'),
  close: require('../assets/icons/icClose.png'),
  close2: require('../assets/icons/close.png'),
  calendar: require('../assets/icons/icCalendarSmall.png'),
  camera: require('../assets/icons/iconCameraWhite.png'),
  chat: require('../assets/icons/btnChat.png'),
  chevronDown: require('../assets/icons/chevronDown.png'),
  chevronRight: require('../assets/icons/ArrowRight.png'),
  checked: require('../assets/icons/checkbox.png'),
  checked2: require('../assets/icons/icChecked.png'),
  circleOrange: require('../assets/icons/icCircle.png'),
  circleGray: require('../assets/icons/icCircleGray.png'),
  contact: require('../assets/icons/lienhe.png'),
  filter: require('../assets/icons/icFilter.png'),
  delete: require('../assets/icons/btnDelete.png'),
  job: require('../assets/icons/icMyJobs.png'),
  jobHL: require('../assets/icons/icMyJobsPress.png'),
  logout: require('../assets/icons/dangxuat.png'),
  more: require('../assets/icons/icMore.png'),
  moreHL: require('../assets/icons/icMorePress.png'),
  notify: require('../assets/icons/icNotify.png'),
  notifyHL: require('../assets/icons/icNotifyPress.png'),
  profile: require('../assets/icons/ttcanhan.png'),
  right: require('../assets/icons/btnRightArrowWhite.png'),
  search: require('../assets/icons/icSearchJob.png'),
  searchWhite: require('../assets/icons/icSearchWhite.png'),
  searchHL: require('../assets/icons/icSearchJobPress.png'),
  send: require('../assets/icons/icChat.png'),
  sendHL: require('../assets/icons/icChatPress.png'),
  unchecked: require('../assets/icons/checkboxHidden.png'),
  unchecked2: require('../assets/icons/icUncheck.png'),
  wallet: require('../assets/icons/vizpay.png'),
  dollar: require('../assets/icons/ic_dollar.png')
}

const Images = {
  avatarShadow: require('../assets/images/bgCircleAvatar.png'),
  card: require('../assets/images/card.png'),
  cardBackground: require('../assets/images/imgBgMoreList.png'),
  chatBackground: require('../assets/images/ChatBackground.png'),
  defaultAvatar: require('../assets/images/defaultAvatar.png'),
  female: require('../assets/images/female.png'),
  job_approved: require('../assets/images/imgApproved.png'),
  job_canceled: require('../assets/images/imgCancel.png'),
  job_completed: require('../assets/images/imgComplete.png'),
  job_rejected: require('../assets/images/imgRejected.png'),
  job_waiting: require('../assets/images/imgPending.png'),
  logo: require('../assets/images/logo_white.png'),
  loginBackground: require('../assets/images/imgLoginBg.png'),
  imagePicker: require('../assets/images/imagePicker.png'),
  male: require('../assets/images/male.png'),
  mailbox: require('../assets/images/mailBox.png'),
  man: require('../assets/images/man.png'),
  man_error: require('../assets/images/man_error.png'),
  man_success: require('../assets/images/man_success.png'),
  moreBackground: require('../assets/images/imgMoreBg.png'),
  review: require('../assets/images/imgReview.png'),
  logoOrange: require('../assets/images/imgLogo.png'),
  logoGrey: require('../assets/images/imgLogoGrey.png')
}

export { Icons, Images }
